services:
  frontend:
    build:
      context: ../blog-app
    ports:
      - 3000:3000
    networks:
      - frontend
    environment:
      REACT_APP_BLOG_API_URL: http://localhost:3030
      PORT: 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./
    restart: always # clean restart of the container with no cache
    expose:
      - 3030
    ports:
      - 3030:3030
    networks:
      - backend
      - frontend
    environment:
      MONGO_URL: mongodb://db:27017/blog
      APP_PORT: 3030
    depends_on:
      - db

  db: # like docker run params 
    image: mongo:latest
    restart: always
    container_name: db
    expose: # no local host access required this is why we use expose instead of ports
      - 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend: {} # use {} to specify it has no other configuration; this is a best practice
  frontend: {}
volumes:
  mongo_data: {}
